name = "MovingLeastSquaresInterpolation"
uuid = "a1716b3e-3eed-4836-b7a8-4159dad2e893"
authors = ["ali-kzm-sh <alikazemzadeh.sh@gmail.com> and contributors"]
version = "0.0.0-DEV"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
LinearAlgebra = "1.11.0"
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
